# Generated by Django 5.2.8 on 2025-12-03 03:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('enunciado', models.TextField()),
                ('linguagem', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#')], max_length=20)),
                ('categoria', models.CharField(choices=[('matematica', 'Matemática'), ('logica', 'Lógica'), ('strings', 'Strings'), ('arrays', 'Arrays'), ('algoritmos', 'Algoritmos'), ('boas_vindas', 'Boas-vindas'), ('recursao', 'Recursão'), ('grafos', 'Grafos')], max_length=30)),
                ('nivel', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='facil', max_length=10)),
                ('pontuacao', models.PositiveSmallIntegerField(default=10, help_text='Pontuação da questão (1 a 100).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('resultado_esperado', models.TextField(help_text='Descrição do resultado esperado (ex: saída do programa).')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
