# Generated by Django 5.2.8 on 2025-12-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pontuacao_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
