# Generated by Django 5.2.8 on 2025-12-10 12:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('codigo_sala', models.CharField(blank=True, db_index=True, default='', help_text='Código único usado para encontrar o evento.', max_length=12, unique=True)),
                ('tipo', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='publico', max_length=10)),
                ('limite_participantes', models.PositiveIntegerField(blank=True, help_text='Deixe vazio para não limitar.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('mensagem_boas_vindas', models.TextField(blank=True, help_text='Mensagem exibida quando o usuário entra na sala.')),
                ('insignia', models.ImageField(blank=True, help_text='Imagem exibida como insígnia do evento.', null=True, upload_to='insignias/')),
                ('senha', models.CharField(blank=True, help_text='Senha do evento', max_length=128)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_criados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrou_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'evento')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='eventos_participando', through='eventos.ParticipacaoEvento', to=settings.AUTH_USER_MODEL),
        ),
    ]
