# Generated by Django 5.2.8 on 2025-12-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='insignia',
            field=models.ImageField(blank=True, null=True, upload_to='insignias/'),
        ),
    ]
