# Generated by Django 5.2.8 on 2025-12-11 13:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_insignia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao_curta', models.CharField(blank=True, max_length=400)),
                ('enunciado', models.TextField()),
                ('pontos', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('tentativas', models.PositiveIntegerField(default=0, help_text='0 = ilimitado')),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('intermediario', 'Intermediário'), ('dificil', 'Difícil')], default='intermediario', max_length=20)),
                ('categoria', models.CharField(choices=[('matematica', 'Matemática'), ('logica', 'Lógica'), ('strings', 'Strings')], default='logica', max_length=50)),
                ('exemplos', models.JSONField(default=list, help_text='Lista de pares {entrada:..., saida:...} mostrados no front')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CasoTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TextField()),
                ('saida_esperada', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_teste', to='eventos.questao')),
            ],
            options={
                'ordering': ('ordem',),
            },
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('linguagem', models.CharField(choices=[('c', 'C'), ('csharp', 'C#'), ('cpp', 'C++'), ('python', 'Python'), ('java', 'Java'), ('javascript', 'Javascript'), ('lua', 'Lua')], max_length=30)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('pontuacao', models.FloatField(blank=True, null=True)),
                ('tentativa_num', models.PositiveIntegerField(default=1)),
                ('judge0_token', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to='eventos.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-enviada_em',),
            },
        ),
        migrations.CreateModel(
            name='ResultadoTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('output', models.TextField(blank=True)),
                ('mensagem', models.TextField(blank=True)),
                ('tempo', models.FloatField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.casoteste')),
                ('submissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='eventos.submissao')),
            ],
        ),
    ]
