# Generated by Django 5.2.8 on 2025-12-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_questao_casoteste_submissao_resultadoteste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoteste',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='questao',
        ),
        migrations.RemoveField(
            model_name='resultadoteste',
            name='submissao',
        ),
        migrations.RemoveField(
            model_name='submissao',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CasoTeste',
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
        migrations.DeleteModel(
            name='ResultadoTeste',
        ),
        migrations.DeleteModel(
            name='Submissao',
        ),
    ]
