# Generated by Django 5.2.8 on 2025-12-10 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('introducao', 'Introdução'), ('sintaxe', 'Sintaxe'), ('variaveis', 'Variáveis'), ('tipos', 'Tipos de Dados'), ('operadores', 'Operadores'), ('lacos', 'Laços de repetição'), ('funcoes', 'Funções')], default='introducao', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('descricao', models.TextField()),
                ('codigo', models.TextField()),
                ('saida_esperada', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='biblioteca.language')),
            ],
            options={
                'ordering': ['language', 'ordem'],
                'unique_together': {('language', 'slug')},
            },
        ),
    ]
