# Generated by Django 5.2.8 on 2025-12-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='Linguagem',
        ),
        migrations.RenameModel(
            old_name='LanguageTopic',
            new_name='TopicoLinguagem',
        ),
    ]
